### ISSUE TITLE
수업이 재미가 없네요.

### ISSUE THREAD

**Issue by googlecampus** [googlecampus/MyApplication#1]
더 재밌게 해주세요. (테스트)

**Comment by seoheecheul** [comment]
저 어제 마지막에 남아서 github 제꺼 프로젝트 연동하는거 관련해서 질문했던 사람입니다.
오늘 여러가지 해보고 블로그도 참고 해서 성공했습니다.
https://github.com/googlecampus/MyApplication (크롬으로 번역해서 ㅋㅋ)

저도 이걸로 제가 아는 사람들에게 그대로 들은 이야기 해주려고 합니다. ^^

**Comment by googlecampus** [comment]
ㅎㅎ 멋지네요. 근데 "수업이 재미가 없네요." 글의 댓글로 달아주셨어요. 오른쪽 상단에 New Issue로 등록해주시면 주제별 구분이 더 쉬울 것 같습니다. ^^
